config/routes.rb
Rails.application.routes.draw do
  resources :shoppers
  resources :orders
  resources :order_items
  resources :items
  resources :customers
  get "/welcome", to: "order_items#welcome", as: "welcome"
  get "/", to: "order_items#homepage", as: "root"
  get "/login", to: "customers#login"
  post "/login", to: "customers#post_login"
  get "/shoppers_login", to: "shoppers#login", as: "shopper_login"
  post "/shoppers_login", to: "shoppers#post_login" 
  get "/logout", to: "customers#logout", as: "logout"
  get "/shoppers_logout", to: "shoppers#logout", as: "shopper_logout"
  get "/shoppers_welcome", to: "shoppers#welcome", as: "shopper_welcome"
  post "/shoppers_pickup/:id", to: "shoppers#pickup", as: "shopper_pickup"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/shopper.rb
class Shopper < ApplicationRecord
    has_many :orders 
    has_many :customers, through: :orders 
    has_secure_password

    validates :name, presence: true
    validates :username, presence: true, uniqueness: true
    validates :address, presence: true
end

app/controllers/shoppers_controller.rb
class ShoppersController < ApplicationController

    before_action :define_variable, only: [:show, :edit, :update, :destroy]
    before_action :restrict_access, only: [:show, :edit, :update, :destroy, :index, :welcome]

    def index

        @shoppers = Shopper.all
        render "index"

    end

    def show

        render "show"

    end

    def new

        @shopper = Shopper.new
        render "new"

    end

    def create

        @shopper = Shopper.create(strong_params(:name, :address, :max_weight, :password, :username))
        if @shopper.save && @shopper.authenticate(params[:shopper][:password])
            session[:current_shopper] = @shopper.id
            redirect_to shopper_welcome_path
        else
            render "new"
        end

    end

    def edit

    end

    def update

    end

    def destroy

    end

    def login
        
        render "login"

    end

    def post_login

        current_user = Shopper.find_by(username: params[:shopper][:username])
        if current_user && current_user.authenticate(params[:shopper][:password])
            session[:current_shopper] = current_user.id
            redirect_to shopper_welcome_path
        else
            flash[:error] = "this user does not exist please try again"
            redirect_to shopper_login_path
        end

    end

    def logout

        session.clear
        flash[:error] = "you have been logged out"
        redirect_to shopper_login_path

    end

    def welcome
    
        @shopper = Shopper.find(session[:current_shopper])

    end

    def pickup

        order = Order.find(params[:id])
        order.update(shopper: Shopper.find(session[:current_shopper]), status: "processed")
        order.save 
        redirect_to shopper_path(session[:current_shopper])

    end


    private 

    def strong_params(*args)

        params.require(:shopper).permit(*args)

    end

    def define_variable

        @shopper = Shopper.find(params[:id])

    end

    def restrict_access

        return head(:forbidden) unless session.include? :current_shopper

    end

end

app/helpers/shoppers_helper.rb
module ShoppersHelper
end

app/views/shoppers/login.html.erb
<h1 class= title><%= render partial: "shared/homeicon"%>Login</h1>

<div class = container-fluid id = log_body_s>
    <div class = container-fluid id = log_form_s> 

        <p id = log_err_s><%=flash[:error]%></p>

        <div id = "form_for_shopper_login">

            <%=form_for :shopper, url: "/shoppers_login", class: "form_horizontal" do |f|%>
            <%=f.label :username%>
            <%=f.text_field :username, class: "form-control", placeholder: "Enter username"%>
            <%=f.label :password%>
            <%=f.password_field :password, class: "form-control", placeholder: "Enter password"%>
            <%=f.submit "login", class:"btn btn-default", id:"log_btn_s"%>

        </div>
    <%end%>
    </div>

    <em>would you like to volunteer to be a <b><u><%=link_to "new shopper", new_shopper_path%></u></b>?</em>
    <em>if you are a customer please click <b><u><%=link_to "here", login_path%></u></b></em>

</div>

app/views/shoppers/new.html.erb
<h1 class = title><%= render partial: "shared/homeicon"%>Sign up as a shopper</h1>
<div class = container-fluid id = new_form_s>

    <div class = container-fluid id = log_err_s>
        <% @shopper.errors.full_messages.each do |e|%>
            <p><%= e %></p>
        <%end %>
    </div>
    <div class = container-fluid id = "form_for_shopper_new">
        <%=form_for @shopper, class:"form_horizontal" do |f|%>
        <%=f.label :name, class: "login_label_c"%>
        <%=f.text_field :name, class: "form-control", placeholder: "Enter your name"%>
        <%=f.label :address, class: "login_label_c"%>
        <%=f.text_area :address, class: "form-control", placeholder: "Enter your address"%>
        <%=f.label "max weight you can carry per order", class: "login_label_c"%>
        <%=f.number_field :max_weight, class: "form-control", placeholder: "max carry weight"%>
        <%=f.label :username, class: "login_label_c"%>
        <%=f.text_field :username, class: "form-control", placeholder: "Enter username"%>
        <%=f.label :password, class: "login_label_c"%>
        <%=f.password_field :password, class: "form-control", placeholder: "Enter password"%>
        <%=f.submit "submit registration", class:"btn btn-default", id:"log_btn_s"%>
        <%end%>
    <div>
</div>

app/views/shoppers/show.html.erb
<h1 class = title><%= render partial: "shared/homeicon"%><%=@shopper.name%></h1>

<div class = container-fluid id = shopper_show_content>
    <div class = container-fluid id = shopper_show_info>
        <h5 id = info_box_header>Info box</h5>
        

        <div class = container-fluid id = shopper_show_orders>
            <p class = free_text>Address: <%=@shopper.address%><p>
            <%if !!@shopper.orders%>
                <p class = free_text>pickup list: </p>

                <ul>
                    <%@shopper.orders.each do |order|%>
                        <li><%=link_to(order.name, order_path(order))%></li>
                        <br>
                    <%end%>
                </ul>

            <%else%>
                <p>no orders picked up. Click <%=link_to("here", orders_path)%> to grab an order!</p>
            <%end%>

        </div>
    </div>

    <div class = free_btn>
        <%=link_to "index", shopper_welcome_path, class: "btn"%>
    </div>
</div>

app/views/shoppers/welcome.html.erb
<h2 class=title ><%= render partial: "shared/homeicon"%>Welcome to BuyStuff</h2>

<div class= container-fluid>

    <ul id = home_links_s>

        <li><%=link_to("shopper", shopper_path(@shopper), class: "btn")%></li>
        <li><%=link_to("items", items_path, class: "btn")%></li>
        <li><%=link_to("orders", orders_path, class: "btn")%></li>
        <li><%=link_to("logout", shopper_logout_path, class: "btn")%></li>
        
    </ul>

</div>