config/routes.rb
Rails.application.routes.draw do
  resources :shoppers
  resources :orders
  resources :order_items
  resources :items
  resources :customers
  get "/welcome", to: "order_items#welcome", as: "welcome"
  get "/", to: "order_items#homepage", as: "root"
  get "/login", to: "customers#login"
  post "/login", to: "customers#post_login"
  get "/shoppers_login", to: "shoppers#login", as: "shopper_login"
  post "/shoppers_login", to: "shoppers#post_login" 
  get "/logout", to: "customers#logout", as: "logout"
  get "/shoppers_logout", to: "shoppers#logout", as: "shopper_logout"
  get "/shoppers_welcome", to: "shoppers#welcome", as: "shopper_welcome"
  post "/shoppers_pickup/:id", to: "shoppers#pickup", as: "shopper_pickup"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :orders 
    has_many :shoppers, through: :orders 
    has_secure_password

    validates :name, presence: true
    validates :address, presence: true, uniqueness: true
    validates :username, presence: true, uniqueness: true

    def self.anyone_there? 

        return !!session[:current_customer]

    end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

    before_action :define_variable, only: [:show, :edit, :update, :destroy]
    before_action :restrict_access, only: [:show, :edit, :update, :destroy, :index]


    def index

        @customers = Customer.all
        render "index"

    end

    def show

        session[:current_user] = params[:id]
        render "show"

    end

    def new
        @customer = Customer.new
        render "new"
    end

    def create
        @customer = Customer.create(strong_params(:name, :address, :password, :username))
        if @customer.save && @customer.authenticate(params[:customer][:password])
            session[:current_user] = @customer.id
            redirect_to welcome_path
        else
            render "new"
        end
    end

    def edit

        render "edit"

    end

    def update

        @customer.update(strong_params(:name, :address))
        if @customer.save
            redirect_to customer_path(@customer)
        else
            redirect_to edit_customer_path
        end 

    end

    def destroy

        @customer.destroy
        redirect_to login_path

    end

    def login #clean up one day 

        render "login"
  
    end

    def post_login
        current_user = Customer.find_by(username: params[:customer][:username])
        if current_user != nil && current_user.authenticate(params[:customer][:password]) 
            session[:current_user] = current_user.id
            redirect_to welcome_path
        else
            flash[:error] = "this user does not exist please try again"
            redirect_to login_path
        end
        
    end

    def logout

        session.clear
        flash[:error] = "you have been logged out"
        redirect_to login_path
    end

    private 

    def strong_params(*args)

        params.require(:customer).permit(*args)

    end

    def define_variable

        @customer = Customer.find(params[:id])

    end

    def restrict_access

        return head(:forbidden) unless session.include? :current_user

    end

end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<h1 class=title><%= render partial: "shared/homeicon"%>Edit your profile</h1>
<div class=box-left>

<% @customer.errors.full_messages.each do |e|%>
    <p><%= e%></p>
<%end%>
<br>
<br>
<%= form_for @customer do |f| %>
    <%= f.label :name%>
    <br>
    <%= f.text_field :name%>
    <br>
    <br>
    <%= f.label :address%>
    <br>
    <%= f.text_area :address%>
    <br>
    <%= f.submit "Change you profile"%>
<%end%>
</div>

app/views/customers/index.html.erb
<h1 class=title><%= render partial: "shared/homeicon"%>Customer Index</h1>
<br>
<br>
<div class=box-left>
<%@customers.each do |customer|%>
    <%=link_to(customer.name, customer_path(customer))%>
    <br>
    <br>
<%end%>

<%= link_to "New Customer", new_customer_path%>
</div>

app/views/customers/login.html.erb
<h1 class= title><%= render partial: "shared/homeicon"%>Login</h1>

<div class = container-fluid id = log_body_c>
    <div class= container id = "log_vid_c">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/FRxII8uYlGo" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
    <div class= container id = "log_form_con">
        <p id = log_err_c><%=flash[:error]%><p>
        <div>
        <%=form_for :customer, url: "/login", :html => {:class => 'form_horizontal'} do |f|%>
            <%=f.label :username, class: "login_label_c"%>
            <%=f.text_field :username,  class: "form-control", placeholder: "Enter username"%>
            <%=f.label :password, class: "login_label_c"%>
            <%=f.password_field :password, class: "form-control", placeholder: "Enter password"%>
            <%=f.submit "login", class:"btn btn-default", id:"log_btn_c"%>
        <%end%>
        </div>
    </div>
    <div class = container-fluid id = not_customer>
        <em><%=link_to "new customer?", new_customer_path%></em>
        <em>if you are a shopper or want to volunteer please click <%=link_to "here", shopper_login_path%></em>
    </div>
</div>

app/views/customers/new.html.erb
<h1 class=title><%= render partial: "shared/homeicon"%>Register as a Customer</h1>
<div class = container-fluid id = new_customer_body>

    <div class = container-fluid id = new_customer_err>  
        <% @customer.errors.full_messages.each do |e|%>
            <p id = customer_form_err><%= e %></p>
            
        <%end%>
    </div>

    <div class = container-fluid id = new_customer_form>  
        <%= form_for @customer, :html => {:class => 'form_horizontal'} do |f| %>
            <%= f.label :name, class: "login_label_c"%>
            <%= f.text_field :name, class: "form-control", placeholder: "Enter name"%>
            <%= f.label :address, class: "login_label_c"%>
            <%= f.text_area :address, class: "form-control", placeholder: "Enter address"%>
            <%= f.label :username, class: "login_label_c"%>
            <%= f.text_field :username, class: "form-control", placeholder: "Enter username"%>
            <%= f.label :password, class: "login_label_c"%>
            <%= f.password_field :password, class: "form-control", placeholder: "Enter password"%>
            <%= f.submit "Register now", class:"btn btn-default", id:"submit_customer"%>
        <%end%>
    </div>
</div>

app/views/customers/show.html.erb
<h1 class= title><%= render partial: "shared/homeicon"%><%=@customer.name.titlecase%></h1>
<div class= container id = show_c>
    <p>Current listed address: <%= @customer.address %></p>

    <div class= continer id = show_orders_c> 
        <h4 id = orders_table_title>Orders Table<h4>
        <%if !@customer.orders.empty?%>
            <h4>Latest Order: </h4>
            <ol id= customer_order>
            <%@customer.orders.last.items.each do |item|%>
                <li><%=item.name%></li>
            <%end%>
            </ol>
            Order Status: <%=@customer.orders.last.status%>
        <%else%>
            <h5>No current orders</h5>
        <%end%>
    </div>

    <%= link_to "Edit Customer", edit_customer_path , class: "btn"%>
    <%= link_to "Delete Customer", customer_path(@customer),class: "btn", method: "delete"%>
    <%= link_to "Return to Index", welcome_path, class: "btn"%>
    <%= link_to "Create an order", new_order_path, class: "btn"%>
</div>