config/routes.rb
Rails.application.routes.draw do
  resources :shoppers
  resources :orders
  resources :order_items
  resources :items
  resources :customers
  get "/welcome", to: "order_items#welcome", as: "welcome"
  get "/", to: "order_items#homepage", as: "root"
  get "/login", to: "customers#login"
  post "/login", to: "customers#post_login"
  get "/shoppers_login", to: "shoppers#login", as: "shopper_login"
  post "/shoppers_login", to: "shoppers#post_login" 
  get "/logout", to: "customers#logout", as: "logout"
  get "/shoppers_logout", to: "shoppers#logout", as: "shopper_logout"
  get "/shoppers_welcome", to: "shoppers#welcome", as: "shopper_welcome"
  post "/shoppers_pickup/:id", to: "shoppers#pickup", as: "shopper_pickup"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    belongs_to :shopper, required: false
    has_many :order_items
    has_many :items, through: :order_items

    validates :item_ids, presence: true 
    validates :name, presence: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

    before_action :define_variable, only: [:show, :edit, :update, :destroy]


    def index

        @orders = Order.where("status = 'pending'")
        render "index"

    end

    def show

        render "show"

    end

    def new

        @order = Order.new
        render "new"

    end

    def create

        @order = Order.create(customer: Customer.find(session[:current_user].to_i), name: params[:order][:name])
        @order.status = "pending"
        @order.item_ids = params[:order][:item_ids]
        
        if @order.save
            redirect_to customer_path(session[:current_user].to_i)
        else
            render "new"
        end

    end

    def edit


    end

    def update

    end

    def destroy

        @order.destroy
        redirect_to shopper_welcome_path

    end

    private 

    def strong_params(*args)

        params.require().permit(*args)

    end

    def define_variable

        @order = Order.find(params[:id])

    end

    def restrict_access

        return head(:forbidden) unless session.include? :current_shopper

    end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<h1 class = title><%= render partial: "shared/homeicon"%>Available Orders</h1>

<div class = container-fluid id = Order_index_content>

    <%if @orders == nil%>
        <p>There are currently no orders available</p>
    <%else%>
        <h5 id = info_box_title>Select an order to deliver<h5>
        <%@orders.each do |order|%>
            <p><%=link_to(order.name, order_path(order), class: "btn")%></p>
        <%end%>
    <%end%>

</div>

<div id = index_btn>

    <%= link_to "Return to Index", shopper_welcome_path, class: "btn"%>
    
</div>

app/views/orders/new.html.erb
<h1 class= title><%= render partial: "shared/homeicon"%>Place your order please</h1>
<div class= box-left>
<%@order.errors.full_messages.each do |message|%>
    <%=message%>
<%end%>

<%=form_for @order do |f|%>
    <p><%=f.label "order name:"%></p>
    <p><%=f.text_field :name%></p>
    <p><%=f.label "please pick your items"%></p>
    <p><%=f.collection_check_boxes(:item_ids, Item.all, :id, :name) do |b|%></p>
        <%=b.check_box%> <%=b.label %>
    <%end%>
    <br>
    <br>
    <%=f.submit "place order"%>

<%end%>
</div>

app/views/orders/show.html.erb
<h1 class = title><%= render partial: "shared/homeicon"%><%=@order.name%></h1>
<div class = container-fluid id = order_show_content>
    <div class = container-fluid id = order_box>
        <h5 id = order_box_title>Order Information:</h5>

        <p class = total_weight>Total Weight: <%=@order.items.sum {|i| i.weight}%></p>
        <h6 id = items_list_header>List:</h6>

        <div class = container-fluid id = order_list_items>
            <ul class = list-inline id = order_list_items_ul>
                <%@order.items.each do |item|%>
                    <li><%=link_to item.name, item_path(item)%></li>
                <%end%>
            </ul>
        </div>

        <p class = text >Customer Information:<p>
        <div class = container-fluid id = customer_info>
            <p class = text>Name: <%=@order.customer.name%></p>
            <p  class = text id = order_show_address>Address: <%=@order.customer.address%></p>
        </div>

    </div>
    <%if !@order.shopper%>
        <%=link_to("Add to Pickup List", shopper_pickup_path(@order), class: "btn", id: "Add_to_btn", method: "post" )%>
    <%end%>

    <%if @order.status == "processed"%>
        <%=link_to("drop off order", order_path(@order), method: "delete")%>
    <%end%>

    <%=link_to("Back to Index", shopper_welcome_path, class: "btn", id: "to_index_btn")%>
<div>